- name: Create VM2 in Chameleon
  openstack.cloud.server:
    cloud: openstack
    state: present
    name: t2-vm2-from-ansible-new
    image: CC-Ubuntu20.04
    flavor: m1.medium
    key_name: cloud-computing
    timeout: 300
    security_groups:
      # - 667273fd-a67a-4ca2-8a68-3088220e6374
      # - 7e09e9fd-4971-49bb-bd55-9aa2fa149b16
      - ENABLE_SSH
      - ENABLE_KAFKA_COUCHDB
      - ENABLE_HTTP_HTTPS
      - ENABLE_ICMP
      - ENABLE_K8S
      - ENABLE_KAFKA_COUCH_SSH
      - ENABLE_WIREGUARD
      - Enable_coch
    floating_ips: 129.114.25.114
    availability_zone: nova
    nics:
      - net-id: 4b484898-92b4-4a4b-9c5d-7d55bd72f1ee
    # meta:
    #   hostname: t2-vm3-from-ansible
    #   group: uge_master
    wait: yes

- name: Create VM3 in Chameleon
  openstack.cloud.server:
    cloud: openstack
    state: present
    name: t2-vm3-from-ansible
    image: CC-Ubuntu20.04
    flavor: m1.small
    key_name: cloud-computing
    timeout: 300
    security_groups:
      # - 667273fd-a67a-4ca2-8a68-3088220e6374
      # - 7e09e9fd-4971-49bb-bd55-9aa2fa149b16
      - ENABLE_SSH
      - ENABLE_KAFKA_COUCHDB
      - ENABLE_HTTP_HTTPS
      - ENABLE_ICMP
      - ENABLE_K8S
      - ENABLE_KAFKA_COUCH_SSH
      - ENABLE_WIREGUARD
      - Enable_coch
    floating_ips: 129.114.27.202
    availability_zone: nova
    nics:
      - net-id: 4b484898-92b4-4a4b-9c5d-7d55bd72f1ee
    # meta:
    #   hostname: t2-vm3-from-ansible
    #   group: uge_master
    wait: yes
